### ISSUE TITLE
Can I keep the sequences in output files  have the same order as in input files?

### ISSUE THREAD

**Issue by LTEnjoy** [refresh-bio/FAMSA#24]
As shown in the title, when I get an output file, the sequences in it are always in a random order(maybe based on some principles). I wonder can I just keep the sequences in output files have the same order as in input files?
Thanks in advance!

**Comment by agudys** [comment]
Hello,

Sequences are sorted by length due to algorithmic reasons and currently there is no possibility to restore the original order in the output files. However, adding this possibility should be straightforward, thus I mark this as a TODO feature for the next release. Thank you for pointing this out!

Regards,
Adam

**Comment by LTEnjoy** [comment]
Ok, I see. Thank you for your answer! I'm looking forward to the next release.

**Comment by agudys** [comment]
@LTEnjoy 
I have just commited a patch for your request. Please let me know if it works as intended.

Best,
Adam
