### ISSUE TITLE
Low CPU usage?

### ISSUE THREAD

**Issue by pmfawcett** [refresh-bio/FAMSA#36]
Hi,

I'm running 2.1,2 under Windows 10 with a AMD Ryzen 7 4700G 8 Core /16 Logical Processes machine and trying to align a few tens of thousands of protein sequences (~22,000 using the -medoid heuristic).  However, the it seems to be taking much longer than I had expected to calculate the guide tree based on the benchmarks your had published, and I see that CPU usage during guide tree construction is highly variable... it spent a long time initially at only ~7% of CPU, then shot up briefly to near ~100%, but then settles down to only about 30%.  Does this seem right?  I would anticipate that it would stay near 100% throughout the alignment process.  Also, can you confirm that the Windows version makes use of the Vmmem process?

**Comment by agudys** [comment]
Hello,

As for the variable CPU usage, the behaviour you observed is expected. In medoid heuristic, due to algorithmic reasons, it is not that easy to distribute the workload evenly among multiple CPU cores. This, however, should not be a problem since the algorithm is very fast in practice. In particular, the data set you reported should be aligned in seconds. What execution times have you observed exactly? Have you compiled the sources on your own or have you used the precompiled binary? If former is the case, please make sure that you build your sources with Release setting. Otherwise, could you please provide me with your data set? I will try to debug it on my system. 

As for the Vmmem process, as far as I recall, it is related to virtual machines. If you are not using any, there should be no Vmmem CPU/memory consumption.

Regards,
Adam
